workflows:
  my-workflow:
    name: lesson67_ci_cd
    instance_type: mac_mini_m1
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - flutter pub get
      - flutter test
      - flutter build apk
    artifacts:
      - build/**/outputs/**/*.apk
